// cars.js
const cars = [
  { "id":1,"brand":"maruti","model":"Kwid","body":"SUV","fuel":"Hybrid","seats":4,"price":12.4,"image":"https://picsum.photos/seed/car1/800/520","location":{country:"India", state:"Delhi"} },
  { "id":2,"brand":"Maruti Suzuki","model":"Baleno","body":"Hatchback","fuel":"Petrol","seats":5,"price":4.5,"image":"https://picsum.photos/seed/car2/800/520","location":{country:"India", state:"Maharashtra"} },
  { "id":3,"brand":"MG","model":"Rapid","body":"Hatchback","fuel":"Electric","seats":7,"price":11.7,"image":"https://picsum.photos/seed/car3/800/520","location":{country:"United States", state:"California"} },
  { "id":4,"brand":"Maruti Suzuki","model":"Punch","body":"Sedan","fuel":"Petrol","seats":2,"price":11.5,"image":"https://picsum.photos/seed/car4/800/520","location":{country:"India", state:"Uttar Pradesh"} },
  { "id":5,"brand":"MG","model":"Punch","body":"Coupe","fuel":"Petrol","seats":5,"price":25.9,"image":"https://picsum.photos/seed/car5/800/520","location":{country:"UAE", state:"Dubai"} },
  { "id":6,"brand":"Nissan","model":"Civic","body":"SUV","fuel":"Electric","seats":4,"price":28.3,"image":"https://picsum.photos/seed/car6/800/520","location":{country:"Japan", state:"Tokyo"} },
  { "id":7,"brand":"Ford","model":"Baleno","body":"Sedan","fuel":"Diesel","seats":7,"price":32.0,"image":"https://picsum.photos/seed/car7/800/520","location":{country:"United Kingdom", state:"England"} },
  { "id":8,"brand":"Hyundai","model":"i20","body":"SUV","fuel":"Diesel","seats":7,"price":9.8,"image":"https://picsum.photos/seed/car8/800/520","location":{country:"India", state:"Karnataka"} },
  { "id":9,"brand":"Nissan","model":"Civic","body":"Hatchback","fuel":"Petrol","seats":5,"price":23.5,"image":"https://picsum.photos/seed/car9/800/520","location":{country:"Australia", state:"New South Wales"} },
  { "id":10,"brand":"Tata","model":"Kwid","body":"Sedan","fuel":"Electric","seats":4,"price":31.8,"image":"https://picsum.photos/seed/car10/800/520","location":{country:"India", state:"Gujarat"} },
  { "id":11,"brand":"Nissan","model":"Tiago","body":"SUV","fuel":"Petrol","seats":7,"price":11.2,"image":"https://picsum.photos/seed/car11/800/520","location":{country:"India", state:"Rajasthan"} },
  { "id":12,"brand":"Kia","model":"Polo Pro","body":"SUV","fuel":"Electric","seats":5,"price":18.5,"image":"https://picsum.photos/seed/car12/800/520","location":{country:"South Korea", state:"Seoul"} },
  { "id":13,"brand":"Hyundai","model":"Punch","body":"Sedan","fuel":"Electric","seats":5,"price":9.4,"image":"https://picsum.photos/seed/car13/800/520","location":{country:"India", state:"Tamil Nadu"} },
  { "id":14,"brand":"Nissan","model":"Seltos","body":"Sedan","fuel":"Hybrid","seats":5,"price":20.1,"image":"https://picsum.photos/seed/car14/800/520","location":{country:"United States", state:"Texas"} },
  { "id":15,"brand":"Ford","model":"Rapid Pro","body":"Coupe","fuel":"Hybrid","seats":4,"price":27.0,"image":"https://picsum.photos/seed/car15/800/520","location":{country:"Germany", state:"Bavaria"} },
  { "id":16,"brand":"Kia","model":"Harrier","body":"SUV","fuel":"Diesel","seats":2,"price":19.3,"image":"https://picsum.photos/seed/car16/800/520","location":{country:"India", state:"Maharashtra"} },
  { "id":17,"brand":"Honda","model":"Thar","body":"Convertible","fuel":"Diesel","seats":2,"price":26.2,"image":"https://picsum.photos/seed/car17/800/520","location":{country:"India", state:"Rajasthan"} },
  { "id":18,"brand":"Volkswagen","model":"Tiago","body":"Convertible","fuel":"Hybrid","seats":4,"price":7.3,"image":"https://picsum.photos/seed/car18/800/520","location":{country:"Germany", state:"North Rhine-Westphalia"} },
  { "id":19,"brand":"Skoda","model":"Glanza Pro","body":"SUV","fuel":"Petrol","seats":7,"price":20.7,"image":"https://picsum.photos/seed/car19/800/520","location":{country:"Czech Republic", state:"Prague"} },
  { "id":20,"brand":"Hyundai","model":"Safari","body":"Hatchback","fuel":"Electric","seats":5,"price":31.7,"image":"https://picsum.photos/seed/car20/800/520","location":{country:"India", state:"Kerala"} },
  { "id":21,"brand":"Kia","model":"Polo","body":"Sedan","fuel":"Electric","seats":5,"price":13.9,"image":"https://picsum.photos/seed/car21/800/520","location":{country:"India", state:"Telangana"} },
  { "id":22,"brand":"Mahindra","model":"Safari","body":"Hatchback","fuel":"Electric","seats":5,"price":4.0,"image":"https://picsum.photos/seed/car22/800/520","location":{country:"India", state:"West Bengal"} },
  { "id":23,"brand":"Skoda","model":"Hector","body":"MUV","fuel":"CNG","seats":5,"price":8.3,"image":"https://picsum.photos/seed/car23/800/520","location":{country:"India", state:"Bihar"} },
  { "id":24,"brand":"Hyundai","model":"Hector","body":"Coupe","fuel":"Diesel","seats":2,"price":31.6,"image":"https://picsum.photos/seed/car24/800/520","location":{country:"India", state:"Goa"} },
  { "id":25,"brand":"Kia","model":"i20","body":"Convertible","fuel":"Petrol","seats":2,"price":7.2,"image":"https://picsum.photos/seed/car25/800/520","location":{country:"India", state:"Punjab"} },
  { "id":26,"brand":"Tata","model":"Seltos","body":"MUV","fuel":"Hybrid","seats":7,"price":19.6,"image":"https://picsum.photos/seed/car26/800/520","location":{country:"India", state:"Maharashtra"} },
  { "id":27,"brand":"Ford","model":"Seltos","body":"Sedan","fuel":"Hybrid","seats":4,"price":29.5,"image":"https://picsum.photos/seed/car27/800/520","location":{country:"United States", state:"Florida"} },
  { "id":28,"brand":"Volkswagen","model":"Baleno","body":"SUV","fuel":"Hybrid","seats":2,"price":8.4,"image":"https://picsum.photos/seed/car28/800/520","location":{country:"Germany", state:"Hesse"} },
  { "id":29,"brand":"Maruti Suzuki","model":"Rapid","body":"Convertible","fuel":"Diesel","seats":7,"price":11.0,"image":"https://picsum.photos/seed/car29/800/520","location":{country:"India", state:"Assam"} },
  { "id":30,"brand":"Kia","model":"Magnite","body":"Convertible","fuel":"Petrol","seats":5,"price":13.1,"image":"https://picsum.photos/seed/car30/800/520","location":{country:"India", state:"Odisha"} },
  { "id":31,"brand":"MG","model":"EcoSport","body":"MUV","fuel":"Hybrid","seats":7,"price":21.8,"image":"https://picsum.photos/seed/car31/800/520","location":{country:"United Kingdom", state:"Scotland"} },
  { "id":32,"brand":"Hyundai","model":"Hector","body":"Hatchback","fuel":"Electric","seats":5,"price":4.6,"image":"https://picsum.photos/seed/car32/800/520","location":{country:"India", state:"Jharkhand"} },
  { "id":33,"brand":"Renault","model":"Polo","body":"Sedan","fuel":"Diesel","seats":7,"price":9.4,"image":"https://picsum.photos/seed/car33/800/520","location":{country:"France", state:"Île-de-France"} },
  { "id":34,"brand":"Skoda","model":"Polo","body":"Hatchback","fuel":"CNG","seats":5,"price":6.9,"image":"https://picsum.photos/seed/car34/800/520","location":{country:"India", state:"Haryana"} }
];
