const cars=[
{
  "id": 11,
  "brand": "kia",
  "model": "Seltos",
  "body": "SUV",
  "fuel": "Diesel",
  "seats": 5,
  "price": 39.8,
  "image": "https://picsum.photos/seed/car11/800/520",

  "image3d": "https://picsum.photos/seed/car11_3d/900/600",
  "model3d": "models/seltos.glb",

  "year": 2022,
  "engine": "1.5L CRDi Diesel",
  "transmission": "6-Speed Automatic",
  "mileage": "17.8 km/l",
  "topSpeed": "170 km/h",
  "acceleration": "0-100 in 11.1s",
  "colors": ["Silver", "Black", "Orange"],
  "features": ["Ventilated Seats", "Hill Assist", "Rear Camera"],
  "description": "A stylish compact SUV offering comfort, technology, and efficient diesel performance."

},
{
  "id": 21,
  "brand": "bmw",
  "model": "X5",
  "body": "SUV",
  "fuel": "Hybrid",
  "seats": 5,
  "price": 98.4,
  "image": "https://picsum.photos/seed/car21/800/520",

  "image3d": "https://picsum.photos/seed/car21_3d/900/600",
  "model3d": "models/bmw_x5.glb",

  "year": 2024,
  "engine": "3.0L TwinPower Turbo Hybrid",
  "transmission": "8-Speed Automatic",
  "mileage": "14.5 km/l",
  "topSpeed": "250 km/h",
  "acceleration": "0-100 in 5.5s",
  "colors": ["Black", "White", "Blue"],
  "features": ["Heads-Up Display", "Laser Headlights", "Parking Assist"],
  "description": "A premium hybrid SUV with excellent performance, comfort, and advanced luxury features."
},

  {
    "id": 21,
    "brand": "astra",
    "model": "Ravene",
    "body": "SUV",
    "fuel": "Petrol",
    "seats": 5,
    "price": 42.5,
    "image": "https://picsum.photos/seed/car21/800/520",
    "image3d": "https://picsum.photos/seed/car21_3d/900/600",
    "year": 2023,
    "engine": "1.8L Turbo Petrol",
    "transmission": "7-Speed Dual Clutch",
    "mileage": "15.8 km/l",
    "topSpeed": "210 km/h",
    "acceleration": "0-100 in 8.9s",
    "colors": ["Graphite","Pearl White","Midnight Blue"],
    "features": ["Lane Assist","Panoramic Sunroof","Wireless Charging"],
    "description": "A modern compact SUV with sporty handling and premium tech."
  },
  {
    "id": 22,
    "brand": "vela",
    "model": "Orion",
    "body": "Sedan",
    "fuel": "Hybrid",
    "seats": 5,
    "price": 55.0,
    "image": "https://picsum.photos/seed/car22/800/520",
    "image3d": "https://picsum.photos/seed/car22_3d/900/600",
    "year": 2024,
    "engine": "2.0L Hybrid Inline-4",
    "transmission": "8-Speed Automatic",
    "mileage": "20.2 km/l",
    "topSpeed": "230 km/h",
    "acceleration": "0-100 in 7.1s",
    "colors": ["Titanium","Ivory","Obsidian"],
    "features": ["Adaptive Cruise","Heads-Up Display","Heated Seats"],
    "description": "A refined hybrid sedan balancing performance and economy."
  },
  {
    "id": 23,
    "brand": "nova",
    "model": "Zeta",
    "body": "Hatchback",
    "fuel": "Petrol",
    "seats": 5,
    "price": 9.8,
    "image": "https://picsum.photos/seed/car23/800/520",
    "image3d": "https://picsum.photos/seed/car23_3d/900/600",
    "year": 2021,
    "engine": "1.2L Turbo Petrol",
    "transmission": "5-Speed Manual",
    "mileage": "19.6 km/l",
    "topSpeed": "160 km/h",
    "acceleration": "0-100 in 12.6s",
    "colors": ["Cherry Red","Pearl White"],
    "features": ["Rear Camera","Bluetooth Audio","ABS"],
    "description": "An efficient city hatch with nimble handling and modern infotainment."
  },
  {
    "id": 24,
    "brand": "terra",
    "model": "Voyager",
    "body": "MUV",
    "fuel": "Diesel",
    "seats": 7,
    "price": 27.4,
    "image": "https://picsum.photos/seed/car24/800/520",
    "image3d": "https://picsum.photos/seed/car24_3d/900/600",
    "year": 2022,
    "engine": "2.0L Diesel",
    "transmission": "6-Speed Automatic",
    "mileage": "14.2 km/l",
    "topSpeed": "180 km/h",
    "acceleration": "0-100 in 11.8s",
    "colors": ["Sandstone","Metallic Grey"],
    "features": ["7-Seater Layout","AC Zones","Reverse Sensors"],
    "description": "A family MUV with practical space and comfortable ride."
  },
  {
    "id": 25,
    "brand": "orionis",
    "model": "Pulse",
    "body": "Coupe",
    "fuel": "Petrol",
    "seats": 2,
    "price": 68.3,
    "image": "https://picsum.photos/seed/car25/800/520",
    "image3d": "https://picsum.photos/seed/car25_3d/900/600",
    "year": 2024,
    "engine": "3.0L Turbo V6",
    "transmission": "8-Speed Automatic",
    "mileage": "10.4 km/l",
    "topSpeed": "280 km/h",
    "acceleration": "0-100 in 3.9s",
    "colors": ["Racing Red","Carbon Black"],
    "features": ["Launch Control","Active Aero","Performance Brakes"],
    "description": "A high-performance coupe designed for thrilling acceleration and precision."
  },
  {
    "id": 26,
    "brand": "celestia",
    "model": "Eon",
    "body": "Sedan",
    "fuel": "Electric",
    "seats": 5,
    "price": 46.2,
    "image": "https://picsum.photos/seed/car26/800/520",
    "image3d": "https://picsum.photos/seed/car26_3d/900/600",
    "year": 2025,
    "engine": "Dual Motor Electric",
    "transmission": "Single-Speed",
    "mileage": "350 km (WLTP)",
    "topSpeed": "210 km/h",
    "acceleration": "0-100 in 5.2s",
    "colors": ["Pearl White","Slate"],
    "features": ["Fast Charging","Regenerative Braking","360 Camera"],
    "description": "A modern electric sedan with long range and premium interior comfort."
  },
  {
    "id": 27,
    "brand": "lynx",
    "model": "Trail",
    "body": "SUV",
    "fuel": "Diesel",
    "seats": 5,
    "price": 31.5,
    "image": "https://picsum.photos/seed/car27/800/520",
    "image3d": "https://picsum.photos/seed/car27_3d/900/600",
    "year": 2022,
    "engine": "1.9L Diesel",
    "transmission": "6-Speed Manual",
    "mileage": "16.0 km/l",
    "topSpeed": "175 km/h",
    "acceleration": "0-100 in 10.9s",
    "colors": ["Forest Green","Matte Grey"],
    "features": ["All-Wheel Drive","Hill Descent","Tow Hitch"],
    "description": "A rugged SUV built for light off-roading and long journeys."
  },
  {
    "id": 28,
    "brand": "auris",
    "model": "Metro",
    "body": "Hatchback",
    "fuel": "CNG",
    "seats": 5,
    "price": 6.9,
    "image": "https://picsum.photos/seed/car28/800/520",
    "image3d": "https://picsum.photos/seed/car28_3d/900/600",
    "year": 2020,
    "engine": "1.0L CNG-tuned",
    "transmission": "5-Speed Manual",
    "mileage": "28.5 km/kg",
    "topSpeed": "150 km/h",
    "acceleration": "0-100 in 15.4s",
    "colors": ["Sunshine Yellow","White"],
    "features": ["CNG Kit","Low Running Cost","Compact Size"],
    "description": "A city-focused hatchback optimized for low running costs and tight parking."
  },
  {
    "id": 29,
    "brand": "zeno",
    "model": "Stratus",
    "body": "Sedan",
    "fuel": "Petrol",
    "seats": 5,
    "price": 22.1,
    "image": "https://picsum.photos/seed/car29/800/520",
    "image3d": "https://picsum.photos/seed/car29_3d/900/600",
    "year": 2021,
    "engine": "1.5L Turbo Petrol",
    "transmission": "6-Speed Manual",
    "mileage": "17.0 km/l",
    "topSpeed": "190 km/h",
    "acceleration": "0-100 in 10.5s",
    "colors": ["Midnight Black","Silver"],
    "features": ["Cruise Control","Auto Headlamps","Touchscreen"],
    "description": "A balanced sedan offering comfortable commuting and peppy engine performance."
  },
  {
    "id": 30,
    "brand": "vortex",
    "model": "Rift",
    "body": "SUV",
    "fuel": "Hybrid",
    "seats": 5,
    "price": 49.9,
    "image": "https://picsum.photos/seed/car30/800/520",
    "image3d": "https://picsum.photos/seed/car30_3d/900/600",
    "year": 2024,
    "engine": "2.0L Hybrid Turbo",
    "transmission": "CVT",
    "mileage": "21.4 km/l",
    "topSpeed": "205 km/h",
    "acceleration": "0-100 in 7.8s",
    "colors": ["Arctic White","Gunmetal"],
    "features": ["Hybrid Efficiency","AWD","Lane Keep Assist"],
    "description": "A hybrid SUV combining efficiency with confident handling."
  },
  {
    "id": 31,
    "brand": "harbor",
    "model": "Beacon",
    "body": "MUV",
    "fuel": "Petrol",
    "seats": 6,
    "price": 29.5,
    "image": "https://picsum.photos/seed/car31/800/520",
    "image3d": "https://picsum.photos/seed/car31_3d/900/600",
    "year": 2022,
    "engine": "1.8L Naturally Aspirated",
    "transmission": "6-Speed Automatic",
    "mileage": "14.8 km/l",
    "topSpeed": "170 km/h",
    "acceleration": "0-100 in 12.0s",
    "colors": ["Champagne","Black"],
    "features": ["Flexible Seating","Rear AC","Large Boot"],
    "description": "A family-friendly MUV with clever seating and practical storage."
  },
  {
    "id": 32,
    "brand": "quantum",
    "model": "Flux",
    "body": "Coupe",
    "fuel": "Petrol",
    "seats": 4,
    "price": 59.0,
    "image": "https://picsum.photos/seed/car32/800/520",
    "image3d": "https://picsum.photos/seed/car32_3d/900/600",
    "year": 2023,
    "engine": "2.5L Turbo Inline-4",
    "transmission": "8-Speed Automatic",
    "mileage": "11.2 km/l",
    "topSpeed": "260 km/h",
    "acceleration": "0-100 in 4.8s",
    "colors": ["Gloss Black","Silver"],
    "features": ["Active Suspension","Sport Drives","Carbon Trim"],
    "description": "A stylish coupe made for sharp cornering and dynamic drive feel."
  },
  {
    "id": 33,
    "brand": "harrow",
    "model": "Ranger",
    "body": "SUV",
    "fuel": "Diesel",
    "seats": 5,
    "price": 36.7,
    "image": "https://picsum.photos/seed/car33/800/520",
    "image3d": "https://picsum.photos/seed/car33_3d/900/600",
    "year": 2021,
    "engine": "2.2L Diesel",
    "transmission": "6-Speed Manual",
    "mileage": "14.0 km/l",
    "topSpeed": "180 km/h",
    "acceleration": "0-100 in 11.5s",
    "colors": ["Stone Grey","Forest Green"],
    "features": ["Tow Package","Skid Plates","Traction Control"],
    "description": "A practical mid-size SUV built for durability and safe towing."
  },
  {
    "id": 34,
    "brand": "kairo",
    "model": "Spark",
    "body": "Hatchback",
    "fuel": "Petrol",
    "seats": 4,
    "price": 7.9,
    "image": "https://picsum.photos/seed/car34/800/520",
    "image3d": "https://picsum.photos/seed/car34_3d/900/600",
    "year": 2019,
    "engine": "0.9L Turbo Petrol",
    "transmission": "5-Speed Manual",
    "mileage": "20.8 km/l",
    "topSpeed": "145 km/h",
    "acceleration": "0-100 in 14.8s",
    "colors": ["Lemon Yellow","White"],
    "features": ["Compact Size","Easy Parking","Low Insurance"],
    "description": "A budget hatch for urban use with excellent fuel economy."
  },
  {
    "id": 35,
    "brand": "atlas",
    "model": "Summit",
    "body": "SUV",
    "fuel": "Diesel",
    "seats": 7,
    "price": 61.2,
    "image": "https://picsum.photos/seed/car35/800/520",
    "image3d": "https://picsum.photos/seed/car35_3d/900/600",
    "year": 2023,
    "engine": "3.0L Diesel V6",
    "transmission": "9-Speed Automatic",
    "mileage": "12.6 km/l",
    "topSpeed": "220 km/h",
    "acceleration": "0-100 in 7.6s",
    "colors": ["Pearl Black","Royal Blue"],
    "features": ["Third Row Seating","Adaptive Air Suspension","Tow Assist"],
    "description": "A luxurious 7-seater SUV with refined ride and family comfort."
  },
  {
    "id": 36,
    "brand": "velox",
    "model": "Sprint",
    "body": "Hatchback",
    "fuel": "Petrol",
    "seats": 4,
    "price": 12.6,
    "image": "https://picsum.photos/seed/car36/800/520",
    "image3d": "https://picsum.photos/seed/car36_3d/900/600",
    "year": 2022,
    "engine": "1.4L Turbo Petrol",
    "transmission": "6-Speed Manual",
    "mileage": "16.7 km/l",
    "topSpeed": "175 km/h",
    "acceleration": "0-100 in 9.9s",
    "colors": ["Electric Blue","Matte Black"],
    "features": ["Sport Tuned","Rear Spoiler","Touchscreen"],
    "description": "A sporty hatch with crisp steering and engaging power delivery."
  },
  {
    "id": 37,
    "brand": "solis",
    "model": "Aurora",
    "body": "Sedan",
    "fuel": "Petrol",
    "seats": 5,
    "price": 17.8,
    "image": "https://picsum.photos/seed/car37/800/520",
    "image3d": "https://picsum.photos/seed/car37_3d/900/600",
    "year": 2020,
    "engine": "1.6L Naturally Aspirated",
    "transmission": "6-Speed Automatic",
    "mileage": "18.0 km/l",
    "topSpeed": "185 km/h",
    "acceleration": "0-100 in 11.0s",
    "colors": ["Champagne","Grey"],
    "features": ["Eco Mode","Safety Assist","Rear Camera"],
    "description": "A comfortable mid-size sedan designed for smooth everyday driving."
  },
  {
    "id": 38,
    "brand": "bravo",
    "model": "Corsa",
    "body": "Hatchback",
    "fuel": "Petrol",
    "seats": 5,
    "price": 10.4,
    "image": "https://picsum.photos/seed/car38/800/520",
    "image3d": "https://picsum.photos/seed/car38_3d/900/600",
    "year": 2021,
    "engine": "1.0L Turbo Petrol",
    "transmission": "6-Speed Manual",
    "mileage": "19.9 km/l",
    "topSpeed": "165 km/h",
    "acceleration": "0-100 in 13.0s",
    "colors": ["Bright Red","White"],
    "features": ["City Mode","Touchscreen","Rear Parking Assist"],
    "description": "A zippy hatch for urban commuting with modern conveniences."
  },
  {
    "id": 39,
    "brand": "falcon",
    "model": "Apex",
    "body": "Coupe",
    "fuel": "Petrol",
    "seats": 2,
    "price": 74.9,
    "image": "https://picsum.photos/seed/car39/800/520",
    "image3d": "https://picsum.photos/seed/car39_3d/900/600",
    "year": 2024,
    "engine": "3.5L Turbo V6",
    "transmission": "8-Speed Automatic",
    "mileage": "9.8 km/l",
    "topSpeed": "300 km/h",
    "acceleration": "0-100 in 3.6s",
    "colors": ["Jet Black","Crimson"],
    "features": ["Carbon Body Panels","Paddleshift","Sport Differential"],
    "description": "An ultra-performance coupe with race-bred dynamics and luxury touches."
  },
  {
    "id": 40,
    "brand": "equinox",
    "model": "Glide",
    "body": "Sedan",
    "fuel": "Hybrid",
    "seats": 5,
    "price": 33.3,
    "image": "https://picsum.photos/seed/car40/800/520",
    "image3d": "https://picsum.photos/seed/car40_3d/900/600",
    "year": 2023,
    "engine": "1.8L Hybrid",
    "transmission": "CVT",
    "mileage": "22.0 km/l",
    "topSpeed": "200 km/h",
    "acceleration": "0-100 in 8.3s",
    "colors": ["Silver","Deep Blue"],
    "features": ["Hybrid Mode","Smart Key","Lane Assist"],
    "description": "A comfortable hybrid sedan for efficiency-minded drivers."
  },
  {
    "id": 41,
    "brand": "arcus",
    "model": "Nomad",
    "body": "SUV",
    "fuel": "Diesel",
    "seats": 5,
    "price": 28.8,
    "image": "https://picsum.photos/seed/car41/800/520",
    "image3d": "https://picsum.photos/seed/car41_3d/900/600",
    "year": 2022,
    "engine": "2.0L Diesel",
    "transmission": "6-Speed Manual",
    "mileage": "15.0 km/l",
    "topSpeed": "170 km/h",
    "acceleration": "0-100 in 11.2s",
    "colors": ["Canyon Brown","Grey"],
    "features": ["Roof Rails","Rear Diff","Terrain Modes"],
    "description": "A dependable SUV with capability for weekend escapes."
  },
  {
    "id": 42,
    "brand": "britannia",
    "model": "Regal",
    "body": "Sedan",
    "fuel": "Petrol",
    "seats": 5,
    "price": 48.6,
    "image": "https://picsum.photos/seed/car42/800/520",
    "image3d": "https://picsum.photos/seed/car42_3d/900/600",
    "year": 2024,
    "engine": "2.0L Turbo Petrol",
    "transmission": "7-Speed DSG",
    "mileage": "14.9 km/l",
    "topSpeed": "235 km/h",
    "acceleration": "0-100 in 6.6s",
    "colors": ["Midnight Blue","Pearl White"],
    "features": ["Adaptive Cruise","Premium Audio","Massage Seats"],
    "description": "A luxury-focused sedan with high-end comfort and tech."
  },
  {
    "id": 43,
    "brand": "soltera",
    "model": "Breeze",
    "body": "Hatchback",
    "fuel": "Electric",
    "seats": 5,
    "price": 18.0,
    "image": "https://picsum.photos/seed/car43/800/520",
    "image3d": "https://picsum.photos/seed/car43_3d/900/600",
    "year": 2023,
    "engine": "Single Motor Electric",
    "transmission": "Single-Speed",
    "mileage": "280 km (WLTP)",
    "topSpeed": "160 km/h",
    "acceleration": "0-100 in 8.9s",
    "colors": ["Pastel Green","White"],
    "features": ["Fast Charging","Eco Mode","App Integration"],
    "description": "A compact electric hatch ideal for urban commuting with low running cost."
  },
  {
    "id": 44,
    "brand": "cresta",
    "model": "Voyant",
    "body": "SUV",
    "fuel": "Petrol",
    "seats": 5,
    "price": 24.2,
    "image": "https://picsum.photos/seed/car44/800/520",
    "image3d": "https://picsum.photos/seed/car44_3d/900/600",
    "year": 2021,
    "engine": "1.6L Turbo Petrol",
    "transmission": "6-Speed Manual",
    "mileage": "16.9 km/l",
    "topSpeed": "185 km/h",
    "acceleration": "0-100 in 10.7s",
    "colors": ["Pearl White","Titanium"],
    "features": ["Roof Rack","Rear AC","Touch Infotainment"],
    "description": "A compact SUV with modern styling and user-friendly features."
  },
  {
    "id": 45,
    "brand": "orbis",
    "model": "Vector",
    "body": "Sedan",
    "fuel": "Diesel",
    "seats": 5,
    "price": 21.7,
    "image": "https://picsum.photos/seed/car45/800/520",
    "image3d": "https://picsum.photos/seed/car45_3d/900/600",
    "year": 2020,
    "engine": "1.9L Diesel",
    "transmission": "6-Speed Automatic",
    "mileage": "18.3 km/l",
    "topSpeed": "175 km/h",
    "acceleration": "0-100 in 10.8s",
    "colors": ["Ocean Blue","Silver"],
    "features": ["Cruise Control","Rear Parking Sensors","Dual Airbags"],
    "description": "A reliable diesel sedan offering low running costs and smooth ride."
  },

  {
    "id": 46,
    "brand": "Porsche",
    "model": "Cayenne Turbo",
    "body": "SUV",
    "fuel": "Petrol",
    "seats": 5,
    "price": 2.1,
    "image": "https://picsum.photos/seed/porsche46/800/520",
    "year": 2024,
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed Tiptronic S",
    "mileage": "8.2 km/l",
    "topSpeed": "286 km/h",
    "acceleration": "0-100 in 3.7s",
    "colors": ["Carmine Red", "Jet Black", "Chalk"],
    "features": ["Sport Chrono", "Air Suspension", "PDLS Plus", "Carbon Ceramic Brakes"],
    "description": "A high-performance luxury SUV with sports car DNA and breathtaking acceleration.",
    "location": {"country": "Germany", "state": "Baden-Württemberg"}
  },
  {
    "id": 47,
    "brand": "Lexus",
    "model": "LX 600",
    "body": "SUV",
    "fuel": "Petrol",
    "seats": 7,
    "price": 2.8,
    "image": "https://picsum.photos/seed/lexus47/800/520",
    "year": 2024,
    "engine": "3.5L Twin-Turbo V6",
    "transmission": "10-Speed Automatic",
    "mileage": "10.5 km/l",
    "topSpeed": "210 km/h",
    "acceleration": "0-100 in 6.9s",
    "colors": ["Atomic Silver", "Black Onyx", "Nori Green"],
    "features": ["4-Zone Climate", "Mark Levinson Audio", "Rear Seat Entertainment", "Multi-Terrain Select"],
    "description": "A supremely comfortable and capable luxury SUV with unmatched reliability.",
    "location": {"country": "Japan", "state": "Aichi"}
  },
  {
    "id": 48,
    "brand": "Jaguar",
    "model": "F-Pace SVR",
    "body": "SUV",
    "fuel": "Petrol",
    "seats": 5,
    "price": 1.6,
    "image": "https://picsum.photos/seed/jaguar48/800/520",
    "year": 2023,
    "engine": "5.0L Supercharged V8",
    "transmission": "8-Speed Automatic",
    "mileage": "7.8 km/l",
    "topSpeed": "283 km/h",
    "acceleration": "0-100 in 4.0s",
    "colors": ["Eiger Grey", "Santos Blue", "Velocity Blue"],
    "features": ["Active Exhaust", "Configurable Dynamics", "Meridian Audio", "Sports Seats"],
    "description": "A British performance SUV with a roaring V8 and elegant design.",
    "location": {"country": "United Kingdom", "state": "West Midlands"}
  },
  {
    "id": 49,
    "brand": "Volvo",
    "model": "XC90 Recharge",
    "body": "SUV",
    "fuel": "Hybrid",
    "seats": 7,
    "price": 1.2,
    "image": "https://picsum.photos/seed/volvo49/800/520",
    "year": 2024,
    "engine": "2.0L Turbo + Electric",
    "transmission": "8-Speed Automatic",
    "mileage": "45 km/l",
    "topSpeed": "180 km/h",
    "acceleration": "0-100 in 5.4s",
    "colors": ["Thunder Grey", "Onyx Black", "Crystal White"],
    "features": ["Bowers & Wilkins Audio", "Pilot Assist", "Air Suspension", "Clean Zone"],
    "description": "A premium 7-seater SUV with Scandinavian luxury and plug-in hybrid efficiency.",
    "location": {"country": "Sweden", "state": "Gothenburg"}
  },
  {
    "id": 50,
    "brand": "Land Rover",
    "model": "Defender 110",
    "body": "SUV",
    "fuel": "Diesel",
    "seats": 7,
    "price": 1.4,
    "image": "https://picsum.photos/seed/landrover50/800/520",
    "year": 2024,
    "engine": "3.0L Turbo Diesel",
    "transmission": "8-Speed Automatic",
    "mileage": "13.5 km/l",
    "topSpeed": "191 km/h",
    "acceleration": "0-100 in 7.1s",
    "colors": ["Pangea Green", "Fuji White", "Silicon Silver"],
    "features": ["Terrain Response 2", "ClearSight Ground View", "Wade Sensing", "Configurable Terrain"],
    "description": "The iconic off-roader reimagined for modern adventures with uncompromised capability.",
    "location": {"country": "United Kingdom", "state": "Coventry"}
  },
  {
    "id": 51,
    "brand": "Tesla",
    "model": "Model S Plaid",
    "body": "Sedan",
    "fuel": "Electric",
    "seats": 5,
    "price": 2.2,
    "image": "https://picsum.photos/seed/tesla51/800/520",
    "year": 2024,
    "engine": "Tri-Motor Electric",
    "transmission": "Single-Speed",
    "mileage": "637 km (WLTP)",
    "topSpeed": "322 km/h",
    "acceleration": "0-100 in 2.1s",
    "colors": ["Deep Blue", "Pearl White", "Solid Black"],
    "features": ["Yoke Steering", "Plaid Powertrain", "22 Speakers", "Autopilot"],
    "description": "The fastest production car in the world with insane acceleration and cutting-edge tech.",
    "location": {"country": "United States", "state": "California"}
  },
  {
    "id": 52,
    "brand": "Audi",
    "model": "RS e-tron GT",
    "body": "Sedan",
    "fuel": "Electric",
    "seats": 4,
    "price": 2.4,
    "image": "https://picsum.photos/seed/audi52/800/520",
    "year": 2024,
    "engine": "Dual Motor Electric",
    "transmission": "2-Speed Automatic",
    "mileage": "487 km (WLTP)",
    "topSpeed": "250 km/h",
    "acceleration": "0-100 in 3.1s",
    "colors": ["Kemora Grey", "Tactical Green", "Daytona Grey"],
    "features": ["Matrix LED", "RS Sport Suspension", "Bang & Olufsen", "Virtual Cockpit"],
    "description": "A fully electric grand tourer with stunning design and breathtaking performance.",
    "location": {"country": "Germany", "state": "Bavaria"}
  },
  {
    "id": 53,
    "brand": "Mercedes-Benz",
    "model": "EQS 580",
    "body": "Sedan",
    "fuel": "Electric",
    "seats": 5,
    "price": 2.3,
    "image": "https://picsum.photos/seed/mercedes53/800/520",
    "year": 2024,
    "engine": "Dual Motor Electric",
    "transmission": "Single-Speed",
    "mileage": "670 km (WLTP)",
    "topSpeed": "210 km/h",
    "acceleration": "0-100 in 4.1s",
    "colors": ["Obsidian Black", "Hyacinth Red", "Manufaktur Diamond White"],
    "features": ["Hyperscreen", "AIRMATIC", "Burmester Audio", "Rear-Axle Steering"],
    "description": "The electric S-Class with unparalleled luxury, technology, and range.",
    "location": {"country": "Germany", "state": "Baden-Württemberg"}
  },
  {
    "id": 54,
    "brand": "Genesis",
    "model": "G90",
    "body": "Sedan",
    "fuel": "Petrol",
    "seats": 5,
    "price": 1.8,
    "image": "https://picsum.photos/seed/genesis54/800/520",
    "year": 2024,
    "engine": "3.5L Twin-Turbo V6",
    "transmission": "8-Speed Automatic",
    "mileage": "10.2 km/l",
    "topSpeed": "240 km/h",
    "acceleration": "0-100 in 5.7s",
    "colors": ["Havana Red", "Vik Black", "Makaroon Beige"],
    "features": ["Executive Rear Seats", "23 Speakers", "Air Suspension", "Remote Parking"],
    "description": "Korean luxury flagship with exceptional comfort and value proposition.",
    "location": {"country": "South Korea", "state": "Seoul"}
  },
  {
    "id": 55,
    "brand": "Maserati",
    "model": "Ghibli Trofeo",
    "body": "Sedan",
    "fuel": "Petrol",
    "seats": 5,
    "price": 2.0,
    "image": "https://picsum.photos/seed/maserati55/800/520",
    "year": 2024,
    "engine": "3.8L Twin-Turbo V8",
    "transmission": "8-Speed Automatic",
    "mileage": "7.5 km/l",
    "topSpeed": "326 km/h",
    "acceleration": "0-100 in 4.3s",
    "colors": ["Blu Emozione", "Grigio Lamiera", "Rosso Folgore"],
    "features": ["Corsa Mode", "Skyhook Suspension", "Sonus Faber Audio", "Paddle Shifters"],
    "description": "An Italian sports sedan with Ferrari-derived engine and passionate character.",
    "location": {"country": "Italy", "state": "Modena"}
  },
  {
    "id": 56,
    "brand": "Bentley",
    "model": "Continental GT Speed",
    "body": "Coupe",
    "fuel": "Petrol",
    "seats": 4,
    "price": 5.2,
    "image": "https://picsum.photos/seed/bentley56/800/520",
    "year": 2024,
    "engine": "6.0L W12 Twin-Turbo",
    "transmission": "8-Speed Dual-Clutch",
    "mileage": "6.7 km/l",
    "topSpeed": "335 km/h",
    "acceleration": "0-100 in 3.5s",
    "colors": ["Ghost White", "Spectre", "Cricket Ball"],
    "features": ["All-Wheel Steering", "Electronic All-Wheel Drive", "Naim Audio", "Brevetti"],
    "description": "The ultimate grand tourer combining extreme performance with handcrafted luxury.",
    "location": {"country": "United Kingdom", "state": "Crewe"}
  },
  {
    "id": 57,
    "brand": "Aston Martin",
    "model": "DB12",
    "body": "Coupe",
    "fuel": "Petrol",
    "seats": 4,
    "price": 4.8,
    "image": "https://picsum.photos/seed/aston57/800/520",
    "year": 2024,
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "8-Speed Automatic",
    "mileage": "9.2 km/l",
    "topSpeed": "325 km/h",
    "acceleration": "0-100 in 3.5s",
    "colors": ["Satin Xenon Grey", "Ultramarine Black", "Q Buckinghamshire Green"],
    "features": ["Electronic Rear Diff", "Adaptive Suspension", "Bowers & Wilkins", "Track Mode"],
    "description": "The world's first super tourer with breathtaking performance and British elegance.",
    "location": {"country": "United Kingdom", "state": "Gaydon"}
  },
  {
    "id": 58,
    "brand": "Ferrari",
    "model": "Roma",
    "body": "Coupe",
    "fuel": "Petrol",
    "seats": 4,
    "price": 4.5,
    "image": "https://picsum.photos/seed/ferrari58/800/520",
    "year": 2024,
    "engine": "3.9L Twin-Turbo V8",
    "transmission": "8-Speed Dual-Clutch",
    "mileage": "8.5 km/l",
    "topSpeed": "320 km/h",
    "acceleration": "0-100 in 3.4s",
    "colors": ["Rosso Corsa", "Giallo Modena", "Blu Pozzi"],
    "features": ["Side Slip Control", "Manettino", "Ferrari Audio System", "Launch Control"],
    "description": "A front-engined V8 Ferrari with timeless design and accessible performance.",
    "location": {"country": "Italy", "state": "Maranello"}
  },
  {
    "id": 59,
    "brand": "McLaren",
    "model": "GT",
    "body": "Coupe",
    "fuel": "Petrol",
    "seats": 2,
    "price": 4.2,
    "image": "https://picsum.photos/seed/mclaren59/800/520",
    "year": 2024,
    "engine": "4.0L Twin-Turbo V8",
    "transmission": "7-Speed SSG",
    "mileage": "9.1 km/l",
    "topSpeed": "326 km/h",
    "acceleration": "0-100 in 3.2s",
    "colors": ["Mercury Red", "Silica White", "Nardo Blue"],
    "features": ["Proactive Damping", "Variable Drift Control", "Bowers & Wilkins", "Active Dynamics"],
    "description": "A grand touring McLaren focused on comfort without compromising supercar performance.",
    "location": {"country": "United Kingdom", "state": "Woking"}
  },
  
  {
    "id": 61,
    "brand": "Rolls-Royce",
    "model": "Ghost",
    "body": "Sedan",
    "fuel": "Petrol",
    "seats": 5,
    "price": 8.5,
    "image": "https://picsum.photos/seed/rolls61/800/520",
    "year": 2024,
    "engine": "6.75L Twin-Turbo V12",
    "transmission": "8-Speed Automatic",
    "mileage": "6.8 km/l",
    "topSpeed": "250 km/h",
    "acceleration": "0-100 in 4.6s",
    "colors": ["Darkest Tungsten", "Tempest Grey", "Magma Red"],
    "features": ["Planar Suspension", "Whispers App", "Starlight Headliner", "Bespoke Audio"],
    "description": "The most technologically advanced Rolls-Royce with whisper-quiet luxury.",
    "location": {"country": "United Kingdom", "state": "Goodwood"}
  }
  
  
];



